// web/src/components/containers/connection-status/connection-status.tsx
import { Button, Card } from "@mantine/core";
import { modals } from "@mantine/modals";
import { useAppState } from "@/hooks/use-app-state";
import { useClsx } from "@/hooks/use-clsx";
import { ZapIcon } from "lucide-react";

import { InfoStatistic } from "./info-statistic";
import { ClientIndicator } from "./client-indicator";
import { Diagnostics } from "./diagnostics";

export function ConnectionStatus() {
	const { sessionState } = useAppState();
	const { classNames, joinCls } = useClsx({
		icon: {
			"bg-[var(--mantine-color-teal-filled)]/45 text-[var(--mantine-color-teal-9)]":
				sessionState.connectionType === "webrtc",
			"bg-gray-200": sessionState.connectionType === "websocket"
		}
	});

	function onLeave() {
		modals.openConfirmModal({
			title: <span className="font-semibold text-lg">Leave Session</span>,
			children: <span className="text-gray-500">Are you sure you want to leave this session?</span>,
			labels: {
				cancel: "No",
				confirm: "Yes, leave this session"
			},
			size: "sm",
			confirmProps: { color: "red" },
			centered: true,
			onConfirm() {
				window.location.reload();
			}
		});
	}

	return (
		<Card shadow="sm" padding="sm" radius="sm" className="select-none" withBorder>
			<Card.Section py="sm" inheritPadding withBorder>
				<h1 className="font-semibold text-lg leading-snug">Connection Status</h1>
			</Card.Section>

			<Card.Section py="sm" className="space-y-2" inheritPadding>
				<InfoStatistic
					title="Connection type"
					stat={
						<div>
							<p className="inline-block align-middle">
								{sessionState.connectionType === "websocket" ? "WebSocket" : "WebRTC"}
							</p>
							<div className="relative ml-2 inline-flex items-center justify-center align-middle">
								{sessionState.connectionType === "webrtc" && (
									<span className="bg-[var(--mantine-color-teal-filled)]/35 absolute h-8 w-8 animate-ping rounded-full" />
								)}

								<span
									className={joinCls(
										"relative flex h-6 w-6 items-center justify-center rounded-full",
										classNames.icon
									)}
								>
									<ZapIcon size={14} />
								</span>
							</div>
						</div>
					}
				/>
				<InfoStatistic title="Role" stat={sessionState.isHost ? "Host" : "Guest"} />
				<InfoStatistic
					title="Auto WebRTC"
					stat={
						sessionState.autoWebRTC ? (
							<span className="text-[var(--mantine-color-teal-7)] font-semibold">Enabled</span>
						) : (
							<span className="text-[var(--mantine-color-red-7)] font-semibold">Disabled</span>
						)
					}
				/>
				<InfoStatistic
					title="Encryption"
					stat={
						sessionState.encryptionMode !== "none" ? (
							<span className="text-[var(--mantine-color-teal-7)] font-semibold">
								{sessionState.encryptionMode}
							</span>
						) : (
							<span className="text-[var(--mantine-color-red-7)] font-semibold">Disabled</span>
						)
					}
				/>

				<ClientIndicator
					clientsConnected={sessionState.clients.length}
					maximumClients={sessionState.maximumClients}
				/>

				<Diagnostics />

				<Button fullWidth size="sm" color="red" variant="filled" onClick={onLeave}>
					Leave session
				</Button>
			</Card.Section>
		</Card>
	);
}

// web/src/components/session/connection-status/ConnectionStatus.vue
<script setup lang="ts">
import ConfirmDialog from "primevue/confirmdialog";

import StatInformation from "./StatInformation.vue";
import SessionPeers from "./SessionPeers.vue";
import TechnicalDetails from "./TechnicalDetails.vue";

import { Zap } from "lucide-vue-next";
import { useConfirm } from "primevue/useconfirm";
import { applicationState } from "@/state/application";

import { useClsx } from "@/composables/use-clsx";

const { classNames, joinCls } = useClsx({
  icon: {
    "bg-primary/10": applicationState.connection_type === "webrtc",
    "bg-gray-200 dark:bg-gray-600": applicationState.connection_type === "websocket"
  }
});

const confirm = useConfirm();

function confirmExit() {
  confirm.require({
    message: "Are you sure you want to leave this session?",
    header: "Leave Session",
    rejectProps: {
      size: "small",
      severity: "secondary"
    },
    acceptProps: {
      size: "small",
      severity: "danger"
    },
    acceptLabel: "Yes, leave this session",
    blockScroll: true,
    modal: true,
    accept() {
      window.location.reload();
    }
  });
}
</script>

<template>
  <ConfirmDialog v-bind:draggable="false" />
  <Card
    v-bind:pt="{
      content: {
        class: 'space-y-2 select-none'
      },
      footer: {
        class: 'space-y-2'
      }
    }"
  >
    <template #title>Connection Status</template>
    <template #content>
      <StatInformation title="Connection type">
        <template v-if="applicationState.connection_type === 'websocket'" #stat>
          <p>WebSocket</p>
        </template>
        <template v-if="applicationState.connection_type === 'webrtc'" #stat>
          <div>
            <p class="inline-block align-middle">WebRTC</p>
            <div class="relative ml-2 inline-flex items-center justify-center align-middle">
              <span
                class="bg-primary/20 absolute h-8 w-8 animate-ping rounded-full opacity-75"
              ></span>
              <span class="bg-primary/30 absolute h-6 w-6 animate-pulse rounded-full"></span>

              <span
                v-bind:class="
                  joinCls(
                    'relative flex h-5 w-5 items-center justify-center rounded-full',
                    classNames.icon
                  )
                "
              >
                <Zap v-bind:size="12" />
              </span>
            </div>
          </div>
        </template>
      </StatInformation>
      <StatInformation title="Role">
        <template #stat>
          <p v-if="applicationState.is_host">Host</p>
          <p v-else>Guest</p>
        </template>
      </StatInformation>
      <StatInformation title="Auto WebRTC">
        <template #stat>
          <span v-if="applicationState.auto_webrtc" class="text-green-400">Enabled</span>
          <span v-else class="text-red-400">Disabled</span>
        </template>
      </StatInformation>
      <StatInformation title="Encryption">
        <template #stat>
          <span v-if="applicationState.encryption_mode !== 'none'" class="text-green-400">{{
            applicationState.encryption_mode
          }}</span>
          <span v-else class="text-red-400">Disabled</span>
        </template>
      </StatInformation>

      <SessionPeers />
      <TechnicalDetails />
    </template>
    <template #footer>
      <Button v-on:click="confirmExit" severity="danger" size="small" fluid> Leave session </Button>
    </template>
  </Card>
</template>
