// web/src/views/session/ActiveSession.vue
<script setup lang="ts">
import CopyToClipboard from "@/components/CopyToClipboard.vue";
import ActivityLog from "@/components/session/ActivityLog.vue";

import ConnectionStatus from "@/components/session/connection-status/ConnectionStatus.vue";
import WaitingForHost from "@/components/session/connection-state/WaitingForHost.vue";
import DirectConnectionPrompt from "@/components/session/connection-state/DirectConnectionPrompt.vue";
import FileTransfer from "@/components/session/file-transfer/FileTransfer.vue";
import WaitingForConnections from "@/components/session/connection-state/WaitingForConnections.vue";
import DeveloperControls from "@/components/session/DeveloperControls.vue";

import { websocketState } from "@/state/websocket";
import { WebSocketClient } from "@/lib/websocket";
import { onBeforeMount } from "vue";
import { useRouter } from "vue-router";

import { Crown, Copy, Wifi, Router, TriangleAlert } from "lucide-vue-next";

const router = useRouter();

onBeforeMount(() => {
  if (websocketState.connection_type === "none") {
    router.push("/session/create");
  }
});
</script>

<template>
  <template v-if="websocketState.is_connected && websocketState.connection_type != 'none'">
    <Message severity="warn" class="w-full select-none">
      <template #icon>
        <TriangleAlert v-bind:size="20" />
      </template>
      <span class="font-light">
        All received files will be lost when you close this tab or browser. Download any files you
        want to keep.
      </span></Message
    >

    <DeveloperControls />

    <div class="relative flex w-full items-center justify-between select-none">
      <div class="flex items-center justify-between gap-x-2">
        <CopyToClipboard
          v-if="websocketState.session_code"
          v-bind:value="websocketState.session_code"
        >
          <Button variant="text" severity="contrast" class="text-gray-500 hover:bg-gray-100!">
            <span class="font-mono text-base">{{ websocketState.session_code }}</span>
            <Copy v-bind:size="18" class="ml-2" />
          </Button>
        </CopyToClipboard>

        <Badge v-if="websocketState.connection_type === 'signal'" severity="secondary">
          <Wifi v-bind:size="14" />
          <span class="ml-2 font-medium">Server Connection</span>
        </Badge>
        <Badge v-if="websocketState.connection_type === 'direct'" severity="success">
          <Router v-bind:size="14" />
          <span class="ml-2 font-medium">Direct Connection</span>
        </Badge>
      </div>

      <Button
        v-if="websocketState.is_host && websocketState.connection_type === 'signal'"
        v-on:click="WebSocketClient.emit('transfer_host_request', {})"
        severity="contrast"
        size="small"
      >
        <Crown v-bind:size="18" />
        Transfer host
      </Button>
    </div>

    <div class="grid w-full grid-cols-3 gap-4">
      <div class="col-span-1 space-y-4">
        <ConnectionStatus />
        <ActivityLog v-bind:logs="[]" />
      </div>

      <div class="col-span-2">
        <template v-if="websocketState.is_host">
          <WaitingForConnections
            v-if="websocketState.clients.length !== websocketState.maximum_clients"
          />
          <FileTransfer v-else-if="websocketState.connection_type === 'direct'" />
          <DirectConnectionPrompt v-else-if="websocketState.connection_type === 'signal'" />
        </template>

        <template v-else>
          <WaitingForHost v-if="websocketState.connection_type === 'signal'" />
          <FileTransfer v-else-if="websocketState.connection_type === 'direct'" />
        </template>
      </div>
    </div>
  </template>

  <template v-else>
    <p>You are not connected</p>
  </template>
</template>

// web/src/views/session/active-session.tsx
import React, { useState } from "react";

import { LinkIcon, TriangleAlertIcon, XIcon } from "lucide-react";
import { Link } from "react-router";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useAppState } from "@/hooks/use-app-state";
import { ConnectionStatus } from "@/components/connection-status";
import { Collaboration } from "@/components/collaboration";
import { SessionStatusBar } from "@/components/session-status-bar";

export function ActiveSessionView(): React.ReactNode {
	const { sessionState } = useAppState();
	const [showAlert, setShowAlert] = useState(true);

	if (!sessionState.isConnected || sessionState.connectionType === "none") {
		return (
			<Card className="select-none w-md border-x-0 sm:border-x">
				<div className="border-b px-3 sm:px-4 md:px-6 py-3">
					<h2 className="font-semibold text-base md:text-lg">No Active Session</h2>
				</div>

				<div className="flex flex-col items-center justify-center py-16 px-3 sm:px-4 md:px-6 gap-6 text-center">
					<div className="flex p-4 bg-muted">
						<LinkIcon size={32} className="text-muted-foreground" />
					</div>
					<div className="space-y-1.5">
						<h2 className="font-semibold text-base md:text-lg">You are not connected</h2>
						<p className="text-sm text-muted-foreground max-w-xs">
							You need an active session to transfer files. Create a new session or join an existing
							one.
						</p>
					</div>
					<div className="flex items-center gap-0 border divide-x">
						<Link to="/session/create">
							<Button variant="ghost" size="sm" className="gap-1.5 px-4">
								Create session
							</Button>
						</Link>
						<Link to="/session/join">
							<Button variant="ghost" size="sm" className="gap-1.5 px-4">
								Join session
							</Button>
						</Link>
					</div>
				</div>
			</Card>
		);
	}

	return (
		<div className="select-none w-full">
			<div className="border border-b-0 border-x-0 sm:border-x bg-card">
				<SessionStatusBar />

				{showAlert && (
					<div className="border-b bg-yellow-50 px-3 sm:px-4 md:px-6 py-3 flex items-center justify-between gap-4 text-yellow-800 text-sm">
						<div className="flex items-center gap-2">
							<TriangleAlertIcon size={16} className="text-yellow-600 shrink-0" />
							<span>
								All received files will be lost when you close this tab or browser. Download any
								files you want to keep.
							</span>
						</div>
						<button
							type="button"
							onClick={() => setShowAlert(false)}
							className="shrink-0 opacity-70 hover:opacity-100 transition-opacity"
							aria-label="Dismiss"
						>
							<XIcon size={16} />
						</button>
					</div>
				)}

				<div className="h-8 w-full relative border-b">
					<div className="absolute inset-0 bg-[linear-gradient(-45deg,transparent_48%,var(--color-border)_48%,var(--color-border)_52%,transparent_52%)] bg-size-[20px_20px]" />
				</div>
			</div>

			<div className="grid grid-cols-1 md:grid-cols-3 divide-x">
				<div className="md:col-span-1">
					<div className="bg-card border-x-0 border-b border-l border-r-0">
						<ConnectionStatus />
					</div>
				</div>
				<div className="md:col-span-2">
					<div className="bg-card border-x-0 border-b border-r border-l-0">
						<Collaboration />
					</div>
				</div>
			</div>
		</div>
	);
}
