// web/src/components/views/session/create-session.tsx
import React, { useEffect, useRef } from "react";

import {
  CopyIcon,
  CopyCheckIcon,
  ArrowRightIcon,
  ShieldIcon,
  GlobeIcon,
  ClockIcon,
  ChevronLeftIcon
} from "lucide-react";

import { Card, Button, Tooltip, CopyButton, ActionIcon, Group, Box, Stack } from "@mantine/core";
import { AnimatePresence, motion } from "framer-motion";
import { useNavigate } from "react-router";

import { useAppState } from "@/hooks/use-app-state";
import { webSocketClient } from "@/lib/networking";

const VARIANTS = {
  fadeIn: { opacity: 1, y: 0 },
  enter: (direction: number) => ({ y: direction > 0 ? 50 : -50, opacity: 0 }),
  center: { y: 0, opacity: 1, transition: { duration: 0.1 } },
  exit: (direction: number) => ({
    y: direction < 0 ? 50 : -50,
    opacity: 0,
    transition: { duration: 0.1 }
  })
};

export function CreateSessionView() {
  const { sessionState, websocketState, updateState } = useAppState();

  const navigate = useNavigate();
  const isFirstRender = useRef(true);

  useEffect(() => {
    return () => {
      updateState({
        websocketState: {
          isConnecting: false
        },
        webrtcState: {
          isConnecting: false
        }
      });
    };
  }, []);

  return (
    <Card shadow="sm" padding="lg" radius="sm" className="select-none w-md" withBorder>
      <Card.Section withBorder inheritPadding py="md">
        <Group gap="sm">
          <ActionIcon variant="light" size="md" disabled={websocketState.isConnecting}>
            <ChevronLeftIcon size={22} />
          </ActionIcon>
          <h1 className="font-semibold text-lg">Create a session</h1>
        </Group>
      </Card.Section>

      <Card.Section withBorder inheritPadding py="xl">
        <AnimatePresence mode="wait" custom={sessionState.isConnected ? 1 : -1}>
          {sessionState.isConnected ? (
            <motion.div
              key="connected"
              variants={VARIANTS}
              custom={1}
              initial={isFirstRender.current ? { opacity: 0 } : "enter"}
              animate={isFirstRender.current ? "fadeIn" : "center"}
              exit="exit"
              onAnimationComplete={() => {
                isFirstRender.current = false;
              }}
            >
              <h2 className="font-semibold text-lg leading-snug">Session created</h2>
              <p className="text-black/50 leading-snug">
                Share this code with another user to join this session
              </p>

              {sessionState.sessionCode != null && (
                <React.Fragment>
                  <Box p="md" mt="xs" mb="xs" className="rounded border border-gray-200 bg-gray-50">
                    <Group justify="space-between">
                      <p className="font-mono text-sm select-text">{sessionState.sessionCode}</p>
                      <CopyButton value={sessionState.sessionCode}>
                        {({ copy, copied }) => (
                          <Tooltip label={copied ? "Copied!" : "Copy session code"}>
                            <ActionIcon
                              onClick={copy}
                              variant="light"
                              color={copied ? "teal" : "gray"}
                            >
                              {copied ? <CopyCheckIcon size={20} /> : <CopyIcon size={20} />}
                            </ActionIcon>
                          </Tooltip>
                        )}
                      </CopyButton>
                    </Group>
                  </Box>
                  <div className="ml-auto w-fit leading-none">
                    <span className="text-sm text-gray-500">
                      {sessionState.clients.length}/{sessionState.maximumClients} connected
                    </span>
                  </div>
                </React.Fragment>
              )}

              <Box p="md" mt="xs" mb="sm" className="rounded border border-gray-200 bg-gray-50">
                <h3 className="text-base mb-2">Session details</h3>
                <div className="space-y-1 text-sm">
                  <Group justify="space-between">
                    <span className="text-gray-500">Maximum connections:</span>
                    <span className="font-semibold">{sessionState.maximumClients}</span>
                  </Group>
                  <Group justify="space-between">
                    <span className="text-gray-500">Auto WebRTC:</span>
                    {sessionState.autoWebRTC ? (
                      <span className="text-[var(--mantine-color-teal-7)] font-semibold">
                        Enabled
                      </span>
                    ) : (
                      <span className="text-[var(--mantine-color-red-7)] font-semibold">
                        Disabled
                      </span>
                    )}
                  </Group>
                  <Group justify="space-between">
                    <span className="text-gray-500">End-to-end encryption:</span>
                    {sessionState.encryptionMode !== "none" ? (
                      <span className="text-[var(--mantine-color-teal-7)] font-semibold">
                        {sessionState.encryptionMode}
                      </span>
                    ) : (
                      <span className="text-[var(--mantine-color-red-7)] font-semibold">
                        Disabled
                      </span>
                    )}
                  </Group>
                </div>
              </Box>

              <Button
                loading={websocketState.isConnecting}
                size="sm"
                fullWidth
                onClick={() => {
                  navigate(`/session/${sessionState.sessionCode}`);
                }}
              >
                Enter <ArrowRightIcon size={18} />
              </Button>
            </motion.div>
          ) : (
            <motion.div
              key="not-connected"
              variants={VARIANTS}
              custom={-1}
              initial={isFirstRender.current ? { opacity: 0 } : "enter"}
              animate={isFirstRender.current ? "fadeIn" : "center"}
              exit="exit"
              onAnimationComplete={() => {
                isFirstRender.current = false;
              }}
            >
              <h2 className="font-semibold text-lg leading-tight">Start a new session</h2>
              <p className="text-black/50 leading-tight">
                Create a secure session to share files with another person
              </p>

              <Stack mt="xs" mb="sm">
                <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                  <Stack
                    gap={0}
                    align="center"
                    className="rounded-lg border border-gray-200 p-3 text-center"
                  >
                    <ShieldIcon size={30} className="mb-2" />
                    <h3 className="text-sm font-medium">End-to-end Encrypted</h3>
                    <p className="text-xs text-gray-500">Your files stay private</p>
                  </Stack>
                  <Stack
                    gap={0}
                    align="center"
                    className="rounded-lg border border-gray-200 p-3 text-center"
                  >
                    <GlobeIcon size={30} className="mb-2" />
                    <h3 className="text-sm font-medium">Direct Connection</h3>
                    <p className="text-xs text-gray-500">No server storage</p>
                  </Stack>
                </div>
                <Stack
                  gap={0}
                  align="center"
                  className="rounded-lg border border-gray-200 p-3 text-center"
                >
                  <ClockIcon size={30} className="mb-2" />
                  <h3 className="text-sm font-medium">Temporary Sessions</h3>
                  <p className="text-xs text-gray-500">
                    Sessions expire after 30 minutes of inactivity
                  </p>
                </Stack>
              </Stack>

              <Button
                loading={websocketState.isConnecting}
                size="sm"
                fullWidth
                onClick={() => {
                  webSocketClient.connect();
                }}
              >
                Create session
              </Button>
            </motion.div>
          )}
        </AnimatePresence>
      </Card.Section>

      <Card.Section withBorder inheritPadding py="xs" className="h-14">
        <motion.div
          key={
            websocketState.isConnecting
              ? "connecting"
              : sessionState.isConnected
                ? "connected"
                : "idle"
          }
          initial={{ opacity: 0, y: -5 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -5 }}
          transition={{ duration: 0.1 }}
        >
          <Group gap="xs">
            {websocketState.isConnecting ? (
              <p className="text-sm text-gray-500 leading-none mt-2.5">Connecting...</p>
            ) : !sessionState.isConnected ? (
              <React.Fragment>
                <p className="leading-tight text-sm text-gray-500">Already have a session code?</p>
                <Button
                  variant="transparent"
                  px={0}
                  py={0}
                  classNames={{
                    label: "text-sm hover:underline"
                  }}
                  onClick={() => navigate("/session/join")}
                >
                  Join session
                </Button>
              </React.Fragment>
            ) : (
              <p className="my-3 text-sm text-gray-500 leading-none">
                This room will expire in 30 minutes if unused
              </p>
            )}
          </Group>
        </motion.div>
      </Card.Section>
    </Card>
  );
}

// web/src/views/session/CreateSession.vue
<script setup lang="ts">
import SessionDeck from "@/components/session/SessionDeck.vue";
import BackdropGrayCard from "@/components/BackdropGrayCard.vue";
import CopyToClipboard from "@/components/CopyToClipboard.vue";

import { Copy, ArrowRight, Shield, Globe, Clock, Loader2 } from "lucide-vue-next";

import { WebSocketClient } from "@/lib/websocket";
import { websocketState } from "@/state/websocket";
import { sleep } from "@/utils/sleep";

function onConnect() {
  websocketState.is_connecting = true;

  sleep(500).then(WebSocketClient.connect);
}
</script>

<template>
  <SessionDeck v-if="websocketState.is_connected" heading="Create a Session">
    <template #title>Session created</template>
    <template #subtitle>Share this code with another user to join this session</template>
    <template #content>
      <BackdropGrayCard>
        <template #content>
          <div class="flex flex-row items-center justify-between select-none">
            <p class="font-mono text-sm" v-cloak>{{ websocketState.session_code }}</p>

            <CopyToClipboard v-bind:value="websocketState.session_code">
              <Button variant="text" severity="secondary">
                <Copy v-bind:size="20" />
              </Button>
            </CopyToClipboard>
          </div>
        </template>
      </BackdropGrayCard>

      <div class="flex items-center justify-end">
        <p class="text-sm text-gray-500">{{ websocketState.clients.length }}/2 connected</p>
      </div>

      <BackdropGrayCard>
        <template #title>Session details</template>
        <template #content>
          <div class="space-y-1 text-sm">
            <div class="flex justify-between">
              <span class="text-gray-500">Maximum connections:</span>
              <span>{{ websocketState.maximum_clients }}</span>
            </div>
            <div class="flex justify-between">
              <span class="text-gray-500">Auto WebRTC:</span>
              <span class="text-red-400">Disabled</span>
            </div>
            <div class="flex justify-between">
              <span class="text-gray-500">End-to-end encryption:</span>
              <span class="text-red-400">Disabled</span>
            </div>
          </div>
        </template>
      </BackdropGrayCard>
    </template>

    <template #footer>
      <RouterLink
        v-bind:to="{
          name: 'active-session',
          params: { session_code: websocketState.session_code! }
        }"
      >
        <Button color="primary" size="small" fluid>
          Enter
          <ArrowRight v-bind:size="18" />
        </Button>
      </RouterLink>

      <p class="mt-2 text-xs text-gray-500">This room will expire in 30 minutes if unused</p>
    </template>
  </SessionDeck>
  <SessionDeck
    v-else
    heading="Create a Session"
    v-bind:alternative="{
      text: 'Already have a session code?',
      link: '/session/join',
      linkText: 'Join session'
    }"
  >
    <template #title>Start a new session</template>
    <template #subtitle>Create a secure session to share files with another person</template>
    <template #content>
      <div class="space-y-4">
        <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
          <div class="flex flex-col items-center rounded-lg border border-gray-200 p-3 text-center">
            <Shield v-bind:size="30" class="mb-2" />
            <h3 class="text-sm font-medium">End-to-End Encrypted</h3>
            <p class="text-xs text-gray-500">Your files stay private</p>
          </div>
          <div class="flex flex-col items-center rounded-lg border border-gray-200 p-3 text-center">
            <Globe v-bind:size="30" class="mb-2" />
            <h3 class="text-sm font-medium">Direct Connection</h3>
            <p class="text-xs text-gray-500">No server storage</p>
          </div>
        </div>
        <div class="flex flex-col items-center rounded-lg border border-gray-200 p-3 text-center">
          <Clock v-bind:size="30" class="mb-2" />
          <h3 class="text-sm font-medium">Temporary Sessions</h3>
          <p class="text-xs text-gray-500">Rooms expire after 30 minutes of inactivity</p>
        </div>
      </div>
    </template>

    <template #footer>
      <Button
        v-bind:disabled="websocketState.is_connecting"
        v-on:click="onConnect"
        size="small"
        fluid
      >
        <Loader2 v-if="websocketState.is_connecting" v-bind:size="18" class="mr-2 animate-spin" />
        {{ websocketState.is_connecting ? "Creating session..." : "Create session" }}
      </Button>
    </template>
  </SessionDeck>
</template>
