// web/src/views/session/create-session.tsx
import React, { useEffect } from "react";
import { ArrowRightIcon, ChevronLeftIcon } from "lucide-react";
import { Link, useNavigate } from "react-router";

import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { CopyButton } from "@/components/ui/copy-button";
import { WEBSITE_FEATURES } from "@/config/constants";
import { useAppState } from "@/hooks/use-app-state";
import { appState } from "@/state";
import { getWebSocketClient } from "@/lib/networking/client-registry";

const FEATURE_HIGHLIGHTS = [...WEBSITE_FEATURES].sort(() => Math.random() - 0.5).slice(0, 3);

export function CreateSessionView(): React.ReactNode {
	const { sessionState, websocketState } = useAppState();

	const navigate = useNavigate();

	useEffect(() => {
		return (): void => {
			appState.dispatch("RESET_CONNECTING_STATES", null);
		};
	}, []);

	return (
		<Card className="select-none w-md">
			<CardHeader className="border-b">
				<div className="flex items-center justify-between">
					<div className="border-r">
						<Link to="/">
							<Button
								className="h-16 w-16"
								variant="secondary"
								size="icon"
								disabled={websocketState.isConnecting}
							>
								<ChevronLeftIcon size={22} />
							</Button>
						</Link>
					</div>
					<h2 className="font-semibold text-base md:text-lg pr-3 sm:pr-4 md:pr-6">Create a session</h2>
				</div>
			</CardHeader>

			<CardContent className="border-b py-0 px-0">
				{sessionState.isConnected ? (
					<React.Fragment>
						<div className="p-3 sm:p-4 md:p-6">
							<h2 className="font-semibold text-base md:text-lg leading-snug">Session created</h2>
							<p className="text-muted-foreground leading-snug text-sm">
								Share this code with another user to join this session
							</p>
						</div>

						<div className="h-8 w-full relative border-t">
							<div className="absolute inset-0 bg-[linear-gradient(-45deg,transparent_48%,var(--color-border)_48%,var(--color-border)_52%,transparent_52%)] bg-size-[20px_20px]" />
						</div>

						{sessionState.sessionCode !== null && (
							<React.Fragment>
								<div className="px-3 sm:px-4 md:px-6 py-3 border-y bg-secondary">
									<div className="flex items-center justify-between">
										<p className="font-mono text-sm select-text">{sessionState.sessionCode}</p>
										<CopyButton value={sessionState.sessionCode} />
									</div>
								</div>
								<div className="ml-auto w-fit leading-none py-3 px-3 sm:px-4 md:px-6">
									<span className="text-sm text-muted-foreground">
										{sessionState.clients.length}/{sessionState.maximumClients} connected
									</span>
								</div>
							</React.Fragment>
						)}

						<div className="p-3 sm:p-4 md:p-6 border-y bg-secondary">
							<h3 className="text-base mb-2">Session details</h3>
							<div className="space-y-1 text-sm">
								<div className="flex justify-between">
									<span className="text-muted-foreground">Maximum connections:</span>
									<span className="font-semibold">{sessionState.maximumClients}</span>
								</div>
								<div className="flex justify-between">
									<span className="text-muted-foreground">Auto WebRTC:</span>
									{sessionState.autoWebRTC ? (
										<span className="text-primary font-semibold">Enabled</span>
									) : (
										<span className="text-destructive font-semibold">Disabled</span>
									)}
								</div>
								<div className="flex justify-between">
									<span className="text-muted-foreground">End-to-end encryption:</span>
									{sessionState.encryptionMode !== "none" ? (
										<span className="text-primary font-semibold">
											{sessionState.encryptionMode}
										</span>
									) : (
										<span className="text-destructive font-semibold">Disabled</span>
									)}
								</div>
							</div>
						</div>

						<Button
							disabled={websocketState.isConnecting}
							size="sm"
							className="w-full"
							onClick={() => {
								void navigate(`/session/${sessionState.sessionCode}`);
							}}
						>
							{websocketState.isConnecting && (
								<div className="animate-spin rounded-full h-4 w-4 border-2 border-current border-t-transparent" />
							)}
							Enter <ArrowRightIcon size={18} />
						</Button>
					</React.Fragment>
				) : (
					<React.Fragment>
						<div className="p-3 sm:p-4 md:p-6">
							<h2 className="font-semibold text-base md:text-lg leading-snug">Start a new session</h2>
							<p className="text-muted-foreground leading-snug text-sm">
								Create a secure session to share files with another person or device
							</p>
						</div>

						<div className="h-8 w-full relative border-t">
							<div className="absolute inset-0 bg-[linear-gradient(-45deg,transparent_48%,var(--color-border)_48%,var(--color-border)_52%,transparent_52%)] bg-size-[20px_20px]" />
						</div>

						<div className="grid grid-cols-2 divide-x divide-border border-t">
							{FEATURE_HIGHLIGHTS.slice(0, 2).map(({ Icon, title, subDescription }) => (
								<div key={title} className="flex flex-col items-center py-6 text-center">
									<Icon size={22} className="text-primary mb-2" />
									<h3 className="text-sm font-medium">{title}</h3>
									<p className="text-xs text-muted-foreground">{subDescription}</p>
								</div>
							))}
						</div>
						{FEATURE_HIGHLIGHTS[2] &&
							((): React.ReactNode => {
								const { Icon: ThirdIcon, title, subDescription } = FEATURE_HIGHLIGHTS[2];
								return (
									<div className="flex flex-col items-center border-t border-border py-6 text-center">
										<ThirdIcon size={22} className="text-primary mb-2" />
										<h3 className="text-sm font-medium">{title}</h3>
										<p className="text-xs text-muted-foreground">{subDescription}</p>
									</div>
								);
							})()}

						<Button
							disabled={websocketState.isConnecting}
							size="sm"
							className="w-full"
							onClick={() => {
								const ws = getWebSocketClient();
								void ws.connect();
							}}
						>
							{websocketState.isConnecting && (
								<div className="animate-spin rounded-full h-4 w-4 border-2 border-current border-t-transparent" />
							)}
							Create session
						</Button>
					</React.Fragment>
				)}
			</CardContent>

			<div className="h-8 w-full relative border-b">
				<div className="absolute inset-0 bg-[linear-gradient(45deg,transparent_48%,var(--color-border)_48%,var(--color-border)_52%,transparent_52%)] bg-size-[20px_20px]" />
			</div>

			<div className="pl-3 sm:pl-4 md:pl-6 h-14">
				<div className="w-full h-full flex items-stretch justify-between gap-6">
					{websocketState.isConnecting ? (
						<p className="text-sm text-muted-foreground flex items-center">Connecting...</p>
					) : !sessionState.isConnected ? (
						<React.Fragment>
							<div className="flex items-center">
								<p className="text-sm text-muted-foreground">Already have a session code?</p>
							</div>
							<div className="flex items-center border-l px-3 sm:px-4 md:px-6 bg-secondary">
								<Link to="/session/join">
									<Button variant="link" size="sm" className="px-0 py-0 text-sm h-auto">
										Join session
									</Button>
								</Link>
							</div>
						</React.Fragment>
					) : (
						<p className="text-sm text-muted-foreground flex items-center">
							This room will expire in 30 minutes if unused
						</p>
					)}
				</div>
			</div>
		</Card>
	);
}

// web/src/views/session/CreateSession.vue
<script setup lang="ts">
import SessionDeck from "@/components/session/SessionDeck.vue";
import BackdropGrayCard from "@/components/BackdropGrayCard.vue";

import { Copy, ArrowRight, Shield, Globe, Clock, Loader2 } from "lucide-vue-next";

import { useWebSocket } from "@/composables/use-websocket";
import { websocketState } from "@/state/websocket";
import { sleep } from "@/utils/sleep";

const { connect } = useWebSocket();

function onConnect() {
  websocketState.is_connecting = true;

  sleep(500).then(() => {
    connect();
  });
}
</script>

<template>
  <SessionDeck v-if="websocketState.is_connected" heading="Create a Session">
    <template #title>Session created</template>
    <template #subtitle>Share this code with another user to join this session</template>
    <template #content>
      <BackdropGrayCard>
        <template #content>
          <div class="flex flex-row items-center justify-between select-none">
            <p class="font-mono text-sm" v-cloak>{{ websocketState.session_code }}</p>

            <Button variant="text" severity="secondary">
              <Copy :size="20" />
            </Button>
          </div>
        </template>
      </BackdropGrayCard>

      <div class="flex items-center justify-end">
        <p class="text-sm text-gray-500">{{ websocketState.clients.length }}/2 connected</p>
      </div>

      <BackdropGrayCard>
        <template #title>Session details</template>
        <template #content>
          <div class="space-y-1 text-sm">
            <div class="flex justify-between">
              <span class="text-muted-foreground">Maximum connections:</span>
              <span>{{ websocketState.maximum_clients }}</span>
            </div>
            <div class="flex justify-between">
              <span class="text-muted-foreground">Auto WebRTC:</span>
              <span class="text-red-400">Disabled</span>
            </div>
            <div class="flex justify-between">
              <span class="text-muted-foreground">End-to-end encryption:</span>
              <span class="text-red-400">Disabled</span>
            </div>
          </div>
        </template>
      </BackdropGrayCard>
    </template>

    <template #footer>
      <RouterLink
        :to="{ name: 'active-session', params: { session_code: websocketState.session_code! } }"
      >
        <Button color="primary" size="small" fluid>
          Enter
          <ArrowRight :size="20" />
        </Button>
      </RouterLink>

      <p class="mt-2 text-xs text-gray-500">This room will expire in 30 minutes if unused</p>
    </template>
  </SessionDeck>
  <SessionDeck
    v-else
    heading="Create a Session"
    :alternative="{
      text: 'Already have a session code?',
      link: '/session/join',
      linkText: 'Join session'
    }"
  >
    <template #title>Start a new session</template>
    <template #subtitle>Create a secure session to share files with another person</template>
    <template #content>
      <div class="space-y-4">
        <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
          <div class="flex flex-col items-center rounded-lg border border-gray-200 p-3 text-center">
            <Shield class="mb-2 h-8 w-8" />
            <h3 class="text-sm font-medium">End-to-End Encrypted</h3>
            <p class="text-muted-foreground text-xs">Your files stay private</p>
          </div>
          <div class="flex flex-col items-center rounded-lg border border-gray-200 p-3 text-center">
            <Globe class="mb-2 h-8 w-8" />
            <h3 class="text-sm font-medium">Direct Connection</h3>
            <p class="text-muted-foreground text-xs">No server storage</p>
          </div>
        </div>
        <div class="flex flex-col items-center rounded-lg border border-gray-200 p-3 text-center">
          <Clock class="mb-2 h-8 w-8" />
          <h3 class="text-sm font-medium">Temporary Sessions</h3>
          <p class="text-muted-foreground text-xs">Rooms expire after 30 minutes of inactivity</p>
        </div>
      </div>
    </template>

    <template #footer>
      <Button :disabled="websocketState.is_connecting" v-on:click="onConnect" size="small" fluid>
        <Loader2 v-if="websocketState.is_connecting" class="mr-2 h-4 w-4 animate-spin" />
        {{ websocketState.is_connecting ? "Creating session..." : "Create session" }}
      </Button>
    </template>
  </SessionDeck>
</template>
