// web/src/components/views/session/join-session.tsx
import React, { useEffect } from "react";

import { ArrowRightIcon, ChevronLeftIcon } from "lucide-react";

import { Card, Button, ActionIcon, TextInput, Box, Group } from "@mantine/core";
import { useField } from "@mantine/form";
import { motion } from "framer-motion";

import { useNavigate } from "react-router";
import { useAppState } from "@/hooks/use-app-state";

import { webSocketClient } from "@/lib/networking";
import { SESSION_CODE_EXAMPLE } from "@/config/constants";

const INFO_LIST_POINTS: string[] = [
  "You'll initially connect to our servers",
  "When both users are connected, you can upgrade to a direct connection",
  "File sharing is only available with a direct connection"
];

const REGEX = /^X-[A-Z0-9]{6}$/;

export function JoinSessionView() {
  const { websocketState, sessionState, updateState } = useAppState();

  const navigate = useNavigate();

  const field = useField({
    initialValue: "",
    validate(value) {
      if (!value) {
        return "A session code is required";
      }

      if (!REGEX.test(value)) {
        return `Please enter a valid session code (e.g. ${SESSION_CODE_EXAMPLE})`;
      }

      return null;
    }
  });

  useEffect(() => {
    if (sessionState.isConnected) {
      navigate(`/session/${sessionState.sessionCode}`);
    }
  }, [sessionState.isConnected, sessionState.sessionCode]);

  useEffect(() => {
    return () => {
      updateState({
        websocketState: {
          isConnecting: false
        },
        webrtcState: {
          isConnecting: false
        }
      });
    };
  }, []);

  return (
    <Card shadow="sm" padding="lg" radius="sm" className="select-none w-md" withBorder>
      <Card.Section withBorder inheritPadding py="md">
        <Group gap="sm">
          <ActionIcon variant="light" size="md" disabled={websocketState.isConnecting}>
            <ChevronLeftIcon size={22} />
          </ActionIcon>
          <h1 className="font-semibold text-lg">Join a session</h1>
        </Group>
      </Card.Section>

      <Card.Section withBorder inheritPadding py="xl">
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1, y: 0 }}>
          <h2 className="font-semibold text-lg leading-snug">Enter session code</h2>
          <p className="text-black/50 leading-snug">Ask the session host for their unique code</p>

          <TextInput
            {...field.getInputProps()}
            placeholder={`e.g. ${SESSION_CODE_EXAMPLE}`}
            className="mt-4"
          />

          <Box p="md" my="md" className="rounded border border-gray-200 bg-gray-50">
            <h4 className="text-base">What to expect</h4>
            <ul className="space-y-2 text-sm text-gray-500 mt-2.5">
              {INFO_LIST_POINTS.map((item, index) => (
                <li key={index} className="flex items-start gap-2">
                  <span className="bg-[var(--mantine-primary-color-filled)]/15 mt-0.5 rounded-full p-1">
                    <span className="bg-[var(--mantine-primary-color-filled)]/75 block h-1.5 w-1.5 rounded-full" />
                  </span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </Box>

          <Button
            loading={websocketState.isConnecting}
            size="sm"
            fullWidth
            onClick={async () => {
              !(await field.validate()) && webSocketClient.connect(field.getValue());
            }}
          >
            Enter <ArrowRightIcon size={18} />
          </Button>
        </motion.div>
      </Card.Section>

      <Card.Section withBorder inheritPadding py="xs" className="h-14">
        <motion.div
          key={
            websocketState.isConnecting
              ? "connecting"
              : sessionState.isConnected
                ? "connected"
                : "idle"
          }
          initial={{ opacity: 0, y: -5 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -5 }}
          transition={{ duration: 0.1 }}
        >
          <Group gap="xs">
            {websocketState.isConnecting ? (
              <p className="text-sm text-gray-500 leading-none mt-2.5">Joining...</p>
            ) : !sessionState.isConnected ? (
              <React.Fragment>
                <p className="leading-tight text-sm text-gray-500">Don't have a session code?</p>
                <Button
                  variant="transparent"
                  px={0}
                  py={0}
                  classNames={{
                    label: "text-sm hover:underline"
                  }}
                  onClick={() => navigate("/session/create")}
                >
                  Create session
                </Button>
              </React.Fragment>
            ) : (
              <p className="my-3 text-sm text-gray-500 leading-none">
                This room will expire in 30 minutes if unused
              </p>
            )}
          </Group>
        </motion.div>
      </Card.Section>
    </Card>
  );
}

// web/src/views/session/JoinSession.vue
<script setup lang="ts">
import BackNavigation from "@/components/BackNavigation.vue";

import { ArrowRight } from "lucide-vue-next";

const connectionInfoItems = [
  "You'll initially connect via WebSocket",
  "When both users are connected, you can upgrade to a direct connection",
  "File sharing is only available with a direct connection"
];
</script>

<template>
  <main>
    <div
      class="container mx-auto flex flex-col items-center justify-center gap-4 py-12 not-sm:py-6 md:py-24 lg:py-32"
    >
      <div class="mx-auto w-full max-w-md space-y-6">
        <BackNavigation text="Join a Session" />

        <Card
          class="not-sm:rounded-none! not-sm:border-none! not-sm:shadow-none!"
          :pt="{
            content: {
              class: 'space-y-8'
            }
          }"
        >
          <template #title>Enter Session Code</template>
          <template #subtitle>Ask the session host for their unique code</template>

          <template #content>
            <InputText
              class="rounded! font-mono! text-base! shadow-none!"
              placeholder="e.g. X-4FGS67"
              fluid
            />

            <Card
              class="rounded! border border-gray-200 bg-gray-50! shadow-none! select-none"
              :pt="{
                title: {
                  class: 'text-base!'
                },
                body: {
                  class: 'p-4!'
                },
                content: {
                  class: 'space-y-1'
                }
              }"
            >
              <template #title>What to expect</template>
              <template #content>
                <ul class="text-muted-foreground space-y-2 text-sm">
                  <li
                    v-for="(item, index) in connectionInfoItems"
                    :key="index"
                    class="flex items-start gap-2"
                  >
                    <span class="bg-primary/20 mt-0.5 rounded-full p-1">
                      <span class="bg-primary block h-1.5 w-1.5 rounded-full" />
                    </span>
                    <span>{{ item }}</span>
                  </li>
                </ul>
              </template>
            </Card>
          </template>

          <template #footer>
            <Button color="primary" class="w-full"
              >Join Session
              <ArrowRight :size="20" />
            </Button>
          </template>
        </Card>

        <div class="mt-6 text-center">
          <p class="text-sm text-gray-500">
            Don't have a session code?
            <RouterLink to="/session/create" class="text-primary hover:underline"
              >Create a session</RouterLink
            >
          </p>
        </div>
      </div>
    </div>
  </main>
</template>
