// web/src/components/session/connection-status/ConnectionStatus.vue
<script setup lang="ts">
import ConfirmDialog from "primevue/confirmdialog";

import StatInformation from "./StatInformation.vue";
import SessionPeers from "./SessionPeers.vue";
import TechnicalDetails from "./TechnicalDetails.vue";

import { Zap } from "lucide-vue-next";
import { useConfirm } from "primevue/useconfirm";
import { applicationState } from "@/state/application";

import { useClsx } from "@/composables/use-clsx";

const { classNames, joinCls } = useClsx({
  icon: {
    "bg-primary/10": applicationState.connection_type === "webrtc",
    "bg-gray-200 dark:bg-gray-600": applicationState.connection_type === "websocket"
  }
});

const confirm = useConfirm();

function confirmExit() {
  confirm.require({
    message: "Are you sure you want to leave this session?",
    header: "Leave Session",
    rejectProps: {
      size: "small",
      severity: "secondary"
    },
    acceptProps: {
      size: "small",
      severity: "danger"
    },
    acceptLabel: "Yes, leave this session",
    blockScroll: true,
    modal: true,
    accept() {
      window.location.reload();
    }
  });
}
</script>

<template>
  <ConfirmDialog v-bind:draggable="false" />
  <Card
    v-bind:pt="{
      content: {
        class: 'space-y-2 select-none'
      },
      footer: {
        class: 'space-y-2'
      }
    }"
  >
    <template #title>Connection Status</template>
    <template #content>
      <StatInformation title="Connection type">
        <template v-if="applicationState.connection_type === 'websocket'" #stat>
          <p>WebSocket</p>
        </template>
        <template v-if="applicationState.connection_type === 'webrtc'" #stat>
          <div>
            <p class="inline-block align-middle">WebRTC</p>
            <div class="relative ml-2 inline-flex items-center justify-center align-middle">
              <span
                class="bg-primary/20 absolute h-8 w-8 animate-ping rounded-full opacity-75"
              ></span>
              <span class="bg-primary/30 absolute h-6 w-6 animate-pulse rounded-full"></span>

              <span
                v-bind:class="
                  joinCls(
                    'relative flex h-5 w-5 items-center justify-center rounded-full',
                    classNames.icon
                  )
                "
              >
                <Zap v-bind:size="12" />
              </span>
            </div>
          </div>
        </template>
      </StatInformation>
      <StatInformation title="Role">
        <template #stat>
          <p v-if="applicationState.is_host">Host</p>
          <p v-else>Guest</p>
        </template>
      </StatInformation>
      <StatInformation title="Auto WebRTC">
        <template #stat>
          <span v-if="applicationState.auto_webrtc" class="text-green-400">Enabled</span>
          <span v-else class="text-red-400">Disabled</span>
        </template>
      </StatInformation>
      <StatInformation title="Encryption">
        <template #stat>
          <span v-if="applicationState.encryption_mode !== 'none'" class="text-green-400">{{
            applicationState.encryption_mode
          }}</span>
          <span v-else class="text-red-400">Disabled</span>
        </template>
      </StatInformation>

      <SessionPeers />
      <TechnicalDetails />
    </template>
    <template #footer>
      <Button v-on:click="confirmExit" severity="danger" size="small" fluid> Leave session </Button>
    </template>
  </Card>
</template>

// web/src/components/connection-status/connection-status.tsx
import React from "react";

import { useAppState } from "@/hooks/use-app-state";
import { isAppFeatureEnabled } from "@/state";
import { cn } from "@/lib/utils";
import { ZapIcon } from "lucide-react";

import { InfoStatistic } from "./info-statistic";
import { ClientIndicator } from "./client-indicator";
import { Diagnostics } from "./diagnostics";

export function ConnectionStatus(): React.ReactNode {
	const { sessionState } = useAppState();

	const iconClass = cn(
		"relative flex h-6 w-6 items-center justify-center",
		sessionState.connectionType === "webrtc"
			? "bg-primary bg-primary/20 text-primary"
			: "bg-secondary text-muted-foreground"
	);

	return (
		<div className="h-full flex flex-col">
			<div className="border-b p-3 sm:p-4 md:p-6">
				<h2 className="font-semibold text-base md:text-lg leading-snug">Connection Status</h2>
			</div>

			<div className="p-3 sm:p-4 md:p-6 flex flex-col gap-3">
				<InfoStatistic
					title="Connection type"
					stat={
						<div>
							<p className="inline-block align-middle">
								{sessionState.connectionType === "websocket" ? "WebSocket" : "WebRTC"}
							</p>
							<div className="relative ml-2 inline-flex items-center justify-center align-middle">
								{sessionState.connectionType === "webrtc" && (
									<span className="absolute bg-primary/35 h-8 w-8 animate-ping" />
								)}
								<span className={iconClass}>
									<ZapIcon size={14} />
								</span>
							</div>
						</div>
					}
				/>
				<InfoStatistic title="Role" stat={sessionState.isHost ? "Host" : "Guest"} />
				<InfoStatistic
					title="Auto WebRTC"
					stat={
						isAppFeatureEnabled("auto_webrtc") ? (
							<span className="text-primary font-semibold">Enabled</span>
						) : (
							<span className="text-destructive font-semibold">Disabled</span>
						)
					}
				/>
				<InfoStatistic
					title="Encryption"
					stat={
						isAppFeatureEnabled("encryption_mode") ? (
							<span className="text-primary font-semibold">{sessionState.encryptionMode}</span>
						) : (
							<span className="text-destructive font-semibold">Disabled</span>
						)
					}
				/>

				<ClientIndicator
					clientsConnected={sessionState.clients.length}
					maximumClients={sessionState.maximumClients}
				/>
			</div>

			<Diagnostics />
		</div>
	);
}
